name: Deploy to PostgreSQL

on:
  push:
    branches:
      - main

jobs:
  deploy:
    # runs-on: ubuntu-latest
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install PostgreSQL client
      run: |
        # sudo apt-get update
        # sudo apt-get install -y postgresql-client
        brew update
        brew install libpq
        brew link --force libpq

    - name: Get changed SQL scripts
      id: changed_scripts
      run: |
        # Get a list of changed SQL files in the current commit
        git diff --name-only HEAD^ HEAD ./sql-scripts/*.sql > changed_scripts.txt
        cat changed_scripts.txt
        

    - name: Deploy SQL Script
      env:
        PGHOST: ${{ secrets.PGHOST }}
        PGUSER: ${{ secrets.PGUSER }}
        PGPASSWORD: ${{ secrets.PGPASSWORD }}
        PGDATABASE: ${{ secrets.PGDATABASE }}
      run: |
        # Read the list of changed scripts and run them
        if [ -s changed_scripts.txt ]; then
          for script in $(cat changed_scripts.txt); do
            echo "Running $script..."
            psql -h $PGHOST -U $PGUSER -d $PGDATABASE -f "$script"
          done
        else
          echo "No SQL script changes detected."
        fi

    - name: Verify Deployment
      env:
        PGHOST: ${{ secrets.PGHOST }}
        PGUSER: ${{ secrets.PGUSER }}
        PGPASSWORD: ${{ secrets.PGPASSWORD }}
        PGDATABASE: ${{ secrets.PGDATABASE }}
      run: |
        echo "Verifying deployment..."
        psql -h $PGHOST -U $PGUSER -d $PGDATABASE -c "SELECT NOW();"

    - name: Log Successful Deployment
      run: echo "SQL script successfully deployed to ${{ secrets.PGDATABASE }} at ${{ secrets.PGHOST }}"
