name: Deploy to PostgreSQL

on:
  push:
    branches:
      - main

jobs:
  deploy:
    # runs-on: ubuntu-latest
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install PostgreSQL client
      run: |
        # sudo apt-get update
        # sudo apt-get install -y postgresql-client
        brew update
        brew install libpq
        brew link --force libpq

    # - name: Get changed SQL scripts
    #   id: changed_scripts
    #   run: |
    #     # Check if there is more than one commit
    #     if git rev-parse HEAD^ > /dev/null 2>&1; then
    #       # If there is more than one commit, check for changes in the sql-scripts folder
    #       git diff --name-only HEAD^ HEAD ./sql-scripts/*.sql > changed_scripts.txt
    #     else
    #       # If it's the first commit, assume all scripts need to be run
    #       find ./sql-scripts/*.sql > changed_scripts.txt
    #     fi
    #     # Output the list of changed scripts
    #     cat changed_scripts.txt
        

    - name: Deploy SQL Script
      env:
        PGHOST: ${{ secrets.PGHOST }}
        PGUSER: ${{ secrets.PGUSER }}
        PGPASSWORD: ${{ secrets.PGPASSWORD }}
        PGDATABASE: ${{ secrets.PGDATABASE }}
      run: |
        for script in ./sql-scripts/*.sql; do
        # Check if the script has already been moved to the 'processed' folder
        if [[ -f "./sql-scripts/processed/$(basename $script)" ]]; then
        echo "Skipping $script, already processed."
        continue
        fi

        # Run the SQL script
        psql -h $PGHOST -U $PGUSER -d $PGDATABASE -f "$script"
    
        # Check if the script was executed successfully
        if [ $? -eq 0 ]; then
        echo "script $script ran successfully"
        
        # Make sure the 'processed' folder exists, then move the script to the 'processed' folder
        mkdir -p ./sql-scripts/processed
        mv "$script" ./sql-scripts/processed/
        
        echo "Moved $script to processed folder."
        else
        echo "Error executing $script. Skipping it."
        fi
        done

    - name: Verify Deployment
      env:
        PGHOST: ${{ secrets.PGHOST }}
        PGUSER: ${{ secrets.PGUSER }}
        PGPASSWORD: ${{ secrets.PGPASSWORD }}
        PGDATABASE: ${{ secrets.PGDATABASE }}
      run: |
        echo "Verifying deployment..."
        psql -h $PGHOST -U $PGUSER -d $PGDATABASE -c "SELECT NOW();"

    - name: Log Successful Deployment
      run: echo "SQL script successfully deployed to ${{ secrets.PGDATABASE }} at ${{ secrets.PGHOST }}"
